# Generated by Django 6.0.6 on 2026-08-04 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_author_id_alter_post_id_alter_post_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='posts, null=True, blank=True'),
        ),
    ]
